# Generated by Django 6.0.5 on 2026-05-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("year_of_the_book", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                (
                    "cover",
                    models.CharField(
                        choices=[("Hard", "Hardcover"), ("SOFT", "Softcover")],
                        default="Hard",
                        max_length=4,
                    ),
                ),
                ("inventory", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
